name: LLM Hands on Lab with CML
description: "Hands on Lab which demonstrates a number of concepts including web scraping, vector databases, model deployment, model usage, Langchain, application building, and instruction following/tuning."
author: "Cloudera"
date: "2023-12-20"
specification_version: 1.0
prototype_version: 1.0
environment_variables:
  OPENAI_KEY:
    default: ""
    description: "Access key ID for interacting with OpenAI"

runtimes: 
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Nvidia GPU
  
tasks:
  - type: run_session
    name: Install Dependencies
    script: 0_session-install-deps/install_dependencies.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 12

  - type: run_session
    name: Download/Install Solr
    script: solr/01_install-java11_n_solr.py
    short_summary: Install Java 11
    kernel: python3
    cpu: 2
    memory: 4

  - type: start_application
    name: Solr
    subdomain: solr-app
    script: solr/02_start-solr-application.py
    short_summary: Create and start Solr / Banana
    long_summary: Create and start frontend application. Remember to enable unauthenticated app access for external access to the UI.
    cpu: 2
    memory: 4
    environment_variables:
      TASK_TYPE: START_APPLICATION

  - type: start_application
    name: HIMSS Interface
    subdomain: himss-interface-1
    script: 3_apps/frontend_app.py
    short_summary: Create and start frontend application
    long_summary: Create and start frontend application. Remember to enable unauthenticated app access for external access to the UI.
    cpu: 2
    memory: 4
    environment_variables:
      TASK_TYPE: START_APPLICATION