name: Healthcare Demo
description: "Healthcare demo showcasing Nifi, CML, Solr, and Generative AI functionalities."
author: "Cloudera"
date: "2024-1-29"
specification_version: 1.0
prototype_version: 1.0
environment_variables:
  OPENAI_KEY:
    default: ""
    description: "Access key ID for interacting with OpenAI"

runtimes: 
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Nvidia GPU
  
tasks:
  - type: run_session
    name: Install Dependencies
    script: 0_session-install-deps/install_dependencies.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 12

  - type: run_session
    name: Download/Install Solr and Load Bananna UI
    script: solr/01_install-java11_n_solr.py
    short_summary: Install Java 11
    kernel: python3
    cpu: 2
    memory: 4

  - type: start_application
    name: Solr
    subdomain: solr-app
    script: solr/02_start-solr-application.py
    short_summary: Create and start Solr / Banana
    long_summary: Create and start frontend application. Append /solr/banana/src/index.html#/dashboard to root URL to access Banana UI. Remember to enable unauthenticated app access for external access to the UI.
    cpu: 2
    memory: 4
    environment_variables:
      TASK_TYPE: START_APPLICATION

  - type: start_application
    name: Physician Portal
    subdomain: physician-portal
    script: 3_apps/physician_portal.py
    short_summary: Create and start frontend application
    long_summary: Create and start frontend application. Remember to enable unauthenticated app access for external access to the UI.
    cpu: 2
    memory: 4
    environment_variables:
      TASK_TYPE: START_APPLICATION

  - type: run_session
    name: Create HL7 Data Collection
    script: 4_solr/create-collection.py
    short_summary: Create HL7 collection in Solr
    kernel: python3
    cpu: 1
    memory: 2

  - type: run_session
    name: Generate HL7 Data
    script: 4_solr/generate-hl7-data.py
    short_summary: Generate HL7 Data for processing in Solr
    kernel: python3
    cpu: 1
    memory: 2

  - type: run_session
    name: Push HL7 Data to Solr Collection
    script: 4_solr/push-hl7-to-solr.py
    short_summary: Push/commit HL7 data to Solr collection
    kernel: python3
    cpu: 1
    memory: 2
  
  - type: run_session
    name: Add stopwords to Solr
    script: 4_solr/add-stopwords.py
    short_summary: Add stopwords to Solr collection
    kernel: python3
    cpu: 1
    memory: 2